[project]
name = "trip-sc"
version = "0.1.0"
description = "Trip.com flight scraper using Playwright"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright",
    "pandas",
    "beautifulsoup4",
]
